# Generated by Django 4.0.4 on 2022-05-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_index', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=50)),
                ('survey_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.survey')),
            ],
        ),
    ]
