# Generated by Django 4.0.4 on 2022-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField()),
                ('selected', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('select0', models.TextField(null=True)),
                ('select1', models.TextField(null=True)),
                ('select2', models.TextField(null=True)),
                ('select3', models.TextField(null=True)),
            ],
        ),
    ]
